// This file is automatically generated. Do not edit it directly.
import { createClient, type SupabaseClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = (import.meta.env.VITE_SUPABASE_URL as string | undefined) ?? '';
const SUPABASE_PUBLISHABLE_KEY = (import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY as string | undefined) ?? '';

const missingEnvVars: string[] = [];
if (!SUPABASE_URL) missingEnvVars.push('VITE_SUPABASE_URL');
if (!SUPABASE_PUBLISHABLE_KEY) missingEnvVars.push('VITE_SUPABASE_PUBLISHABLE_KEY');

const isBrowser = typeof window !== 'undefined' && typeof localStorage !== 'undefined';

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabaseConfigError =
  missingEnvVars.length > 0
    ? `Configuração ausente: ${missingEnvVars.join(', ')}`
    : !isBrowser
      ? 'Supabase não disponível fora do navegador'
      : null;

export const supabase: SupabaseClient<Database> | null =
  supabaseConfigError
    ? null
    : createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
        auth: {
          storage: localStorage,
          persistSession: true,
          autoRefreshToken: true,
        },
      });
